version: '3.8'

name: sarama-health-simple

services:
  kafka:
    image: confluentinc/confluent-local:7.6.0
    hostname: broker
    container_name: broker
    ports:
      - "8082:8082"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_NUM_PARTITIONS: '${KAFKA_NUM_PARTITIONS:-3}'
    healthcheck:
      test: [ "CMD", "nc", "-vz", "broker", "29092" ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - sarame-health-simple-network

networks:
  sarame-health-simple-network:
    driver: bridge